from __future__ import annotations

PRIORIDADE_CRITICA = "critica"
PRIORIDADE_ALTA = "alta"
PRIORIDADE_MEDIA = "media"
PRIORIDADE_BAIXA = "baixa"

VALID_PRIORITIES = {
    PRIORIDADE_CRITICA,
    PRIORIDADE_ALTA,
    PRIORIDADE_MEDIA,
    PRIORIDADE_BAIXA,
}

SEVERITY_TO_PRIORITY = {
    "critica": PRIORIDADE_CRITICA,
    "alta": PRIORIDADE_ALTA,
    "media": PRIORIDADE_MEDIA,
    "baixa": PRIORIDADE_BAIXA,
}

PRIORITY_ORDER = {
    PRIORIDADE_CRITICA: 0,
    PRIORIDADE_ALTA: 1,
    PRIORIDADE_MEDIA: 2,
    PRIORIDADE_BAIXA: 3,
}
