from __future__ import annotations

STATUS_NOVA = "nova"
STATUS_TRIAGEM = "triagem"
STATUS_EM_ANDAMENTO = "em_andamento"
STATUS_AGUARDANDO_TERCEIRO = "aguardando_terceiro"
STATUS_AGUARDANDO_REVISAO = "aguardando_revisao"
STATUS_BLOQUEADA = "bloqueada"
STATUS_CONCLUIDA = "concluida"
STATUS_CANCELADA = "cancelada"

VALID_STATUSES = {
    STATUS_NOVA,
    STATUS_TRIAGEM,
    STATUS_EM_ANDAMENTO,
    STATUS_AGUARDANDO_TERCEIRO,
    STATUS_AGUARDANDO_REVISAO,
    STATUS_BLOQUEADA,
    STATUS_CONCLUIDA,
    STATUS_CANCELADA,
}

OPEN_STATUSES = {
    STATUS_NOVA,
    STATUS_TRIAGEM,
    STATUS_EM_ANDAMENTO,
    STATUS_AGUARDANDO_TERCEIRO,
    STATUS_AGUARDANDO_REVISAO,
    STATUS_BLOQUEADA,
}

CLOSED_STATUSES = {STATUS_CONCLUIDA, STATUS_CANCELADA}

